# Site settings
title: Ion
email: the.struggle.1@gmail.com
description: This blog is a one year project to collect thoughts on learning about algorithmic trading. I strive to post every day about the transition from academia to industry and about algorithmic trading from start to finish.
baseurl: "the-struggle" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
